
#################### Installation ########################
https://smorabit.github.io/hdWGCNA/

  cran_packages <- c("hdf5r",
                     "WGCNA",
                     "igraph",
                     "ggraph",
                     "enrichr"))

for (pkg in cran_packages) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg, dependencies = TRUE)
  }
}

bioc_packages <- c("AUCell",
                       "GenomicRanges",
                       "GeneOverlap",
                       "impute",
                       "preprocessCore",
                       "UCell"
)))
for (pkg in bioc_packages) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    BiocManager::install(pkg, ask = FALSE, update = FALSE)
  }
}
 
  ####### Installing hdWGCNA (devtools or github was failing in 02/2026)
  remotes::install_github('smorabit/hdWGCNA', ref='dev')
  

  ########## Installing manualy in BASE
  # Installing issu :
  https://github.com/smorabit/hdWGCNA/issues/335
  
  cd /Users/administrateur/Desktop/Bio_info/Binaries

  git clone https://github.com/smorabit/hdWGCNA.git
  devtools::install_local("/Users/administrateur/Desktop/Bio_info/Binaries/hdWGCNA")

  
  
  ################### TUTO on single-RNA-SEQ #######################
https://smorabit.github.io/hdWGCNA/articles/basic_tutorial.html
# single-cell analysis package
library(Seurat)
library(qs)

# plotting and data science packages
library(tidyverse)
library(cowplot)
library(patchwork)

# co-expression network analysis packages:
library(WGCNA)
library(hdWGCNA)

# using the cowplot theme for ggplot
theme_set(theme_cowplot())

# set random seed for reproducibility
set.seed(12345)

# optionally enable multithreading
enableWGCNAThreads(nThreads = 1)

# loading my obj
# WE DO NOT SUPPORT subsetting the Seurat object after SetupForWGCNA has been run.
hd1<- qread("output_seurat/4_int_obj1_join_vanilla_Reg_nCount_MT_CCdiff_INPROGRESS.qs", nthreads = 12)


variable # use the genes stored in the Seurat object’s VariableFeatures.
fraction # use genes that are expressed in a certain fraction of cells for in the whole dataset or in each group of cells, specified by group.by.
custom   # use genes that are specified in a custom list.

hd1 <- SetupForWGCNA(
  hd1,
  gene_select = "variable", # the gene selection approach
  wgcna_name = "Test1" # the name of the hdWGCNA experiment
)

### Construct metacells
it is a aggreagate generated by KNN --> the point is to reduce sparsity --> Because WGCNA is sensitive to data sparsity

hdWGCNA includes a function MetacellsByGroups to construct metacell expression matrices given a single-cell dataset.
This function constructs a new Seurat object for the metacell dataset which is stored internally in the hdWGCNA experiment. 
We only want to construct metacells from cells that came from the same biological sample of origin, 
--> so it is critical to pass that information to hdWGCNA via the group.by parameter.

Additionally, we usually construct metacells for each cell type separately. 
Thus, in this example, we are grouping by Sample and cell_type to achieve the desired result.

use k values between 20 and 75.
for 40,039 cells, ranging from 890 to 8,188 in each biological sample, and here we used k=25

There should be a range of K values that are suitable for reducing the sparsity while retaining cellular heterogeneity 
for a given dataset, rather than a single optimal value.


NOT GOOD for extremly underrepresented cell type !! --> Cell should be removed using 
  the brain vascular cells (pericytes and endothelial cells) were the least represented, 
  and we have excluded. "min_cells" parameters to exclude groups that are smaller than a specified number of cells. 
--> Errors are likely to arise if the selected value for min_cells is too low.


# construct metacells  in each group
hd1<- MetacellsByGroups(
  seurat_obj = hd1,
  group.by = "orig.ident", # specify the columns in seurat_obj@meta.data to group by / Can be multiple :c("orig.ident", "BAM")
  reduction = 'pca', # select the dimensionality reduction to perform KNN on
  k = 25, # nearest-neighbors parameter
  max_shared = 10, # maximum number of shared cells between two metacells
  ident.group = 'orig.ident' # set the Idents of the metacell seurat object
)

# normalize metacell expression matrix:
hd1 <- NormalizeMetacells(hd1)


# Set up the expression matrix
Here we can subset to our group of interest
use_metacells=TRUE by default by matrix can be used.

hd1 <- SetDatExpr(
  hd1,
  group_name = "D7", # the name of the group of interest in the group.by column
  group.by='orig.ident', # the metadata column containing the cell type info. This same column should have also been used in MetacellsByGroups
  assay = 'RNA', # using RNA assay
  layer = 'data' # using normalized data
)

# Selecting more than one group
#group_name =c( "INH","blabla")

# Select soft-power threshold
hdWGCNA constructs a gene-gene correlation adjacency matrix to infer co-expression relationships between genes. 
The correlations are raised to a power to reduce the amount of noise present in the correlation matrix,
--> BUT it is difficult to determine the soft-power threshold

# Test different soft powers:
hd1 <- TestSoftPowers(
  hd1,
  networkType = 'signed' # you can also use "unsigned" or "signed hybrid"
)
# plot the results:
plot_list <- PlotSoftPowers(hd1)

# assemble with patchwork
png()
wrap_plots(plot_list, ncol=2)

The general guidance is to pick the lowest soft power threshold that has a Scale Free Topology Model Fit greater than or equal to 0.8
Here it woulb be 5

# Power table
power_table <- GetPowerTable(hd1)
head(power_table)


# Construct co-expression network
The parameters for "blockwiseConsensusModules" (of WGCNA) can be passed directly to ConstructNetwork with the same parameter names.

# construct co-expression network:
hd1 <- ConstructNetwork(
  hd1,
  tom_name = 'D7' # name of the topoligical overlap matrix written to disk
)

# Ploting Dendrogram
PlotDendrogram(hd1, main='D7 hdWGCNA Dendrogram')







