#### CELLS TO KEEP
As it is not in vivo / Ex vivo, We do not need to exclude anything



######################## Subseting using subset and metadata #############################################
# Include only Control/Drug
sub_obj <- subset(seurat_object, subset = treatment %in% c("Control", "Drug"))
# Include ALL Except Control/Drug
sub_obj <- subset(seurat_object, subset = !(treatment %in% c("Control", "Drug")))



####### Required library : SeuratWrappers / batchelor)
# "cells_to_keep" have been generated by removing 2 group outliers of 5-10 cells
# We can identify the cell directly by their UMAP coordinates$
# embeddings[,1] = cut vertically  / on X axis
# embeddings[,2] = cut horizontally / on Y axis


cells_to_keep <- names(which(pre_obj_b@reductions$umap@cell.embeddings[,1]<= 5))

  DimPlot( join_obj_1, reduction = 'umap', group.by = 'Phase') + 
    ggplot2::geom_hline(yintercept = 4.2, col= 'blue')
  
  DimPlot( join_obj_1, reduction = 'umap', group.by = 'Phase') + 
    ggplot2::geom_vline(xintercept = 3, col= 'red')

  
qsave(cells_to_keep, "2b_cells_to_keep_RT_in_vivo2.qs")
  
  
  
  
################## Cutting in diagonale :  y=ax+b #######################  

cells_to_keep <- names(which( pre_obj_b@reductions$umap@cell.embeddings[,2] <= 1*pre_obj_b@reductions$umap@cell.embeddings[,2] + 5))


  DimPlot( join_obj_1, reduction = 'umap', group.by = 'Phase') + 
    ggplot2::geom_abline(slope = -1,intercept = 5.6 , col= 'blue')





qsave(cells_to_keep, "2b_cells_to_keep_RT_in_vivo2.qs")







################ USING CEREBRO EXPORT to export the data and cercle the pop I want !!!  ###############################################   

#remotes::install_github("erzakiev/cerebroAppWithLocalStorage@ubuntu")

# Exporting
cerebroApp::exportFromSeurat(
  FlattenEmbeds4Cerebro(pre_obj_b, ignore2d = T),
  assay = 'RNA', 
  groups = colnames(pre_obj_b@meta.data), # it will group by this on cerebro
  nUMI = "nCount_RNA", nGene = "nFeature_RNA", 
  experiment_name ="RT_in_vivo2_complement", 
  organism = "mouse", 
  file = "2b_pre_obj_b_vanilla.crb",
)

### Saving first step for Imene
qsave(pre_obj_b, "output_seurat/2_Pre_obj_b_vanilla_cutoff1600_for_imene.qs", nthreads = 12)



# Launching cererbo locally to visuallise

cerebroApp::launchCerebroV1.3(crb_file_to_load = "2b_pre_obj_b_vanilla.crb")
# from TERMINAL check which open gate there is and test it 
netstat -anvp tcp | awk 'NR<3 || /LISTEN/'
# Should finish with 4 digit exactly and add ":" just before !!
#http://127.0.0.1:3119/


#### I selected manually using the lasso on cerebro
selection_cererbo <- read_csv("/Users/administrateur/Desktop/Bio_info/Single_Cell/RT_in_vivo_continuous2_complement/data/2b_RT_in_vivo2_cells_to_keep_from_cerebro_selected_cells.csv")

cells_to_keep <- selection_cererbo %>% select (cell_barcode) %>% unlist() ### 6787 cells (unlist to break the table to a vector)

qsave(cells_to_keep, "2b_cells_to_keep_RT_in_vivo2.qs")






######### Curation of tiny clusters
#### Creating curated DBscan cluster --> eliminating tiny cluster <100
int_obj1$optics_dbscan10_minptseps_cl0.25_curated <- int_obj1$optics_dbscan10_minptseps_cl0.25
table(int_obj1$optics_dbscan10_minptseps_cl0.25_curated)

# Subseting the tiny clusters
tiny_cluster <- names(which(table(int_obj1$optics_dbscan10_minptseps_cl0.25_curated) <100))
tiny_cluster
# getting the UMI in the 
tiny_cluster_UMI <-  int_obj1@meta.data %>% filter(optics_dbscan10_minptseps_cl0.25_curated %in%  tiny_cluster) %>% rownames()


# Renaming all tiny cluster to NA
int_obj1$optics_dbscan10_minptseps_cl0.25_curated[names(int_obj1$optics_dbscan10_minptseps_cl0.25_curated) %in% tiny_cluster_UMI] <- NA
table(int_obj1$optics_dbscan10_minptseps_cl0.25_curated)

##### Renaming all cluster in a sequenced number
#### using factors
int_obj1$optics_dbscan10_minptseps_cl0.25_curated <- as.factor(int_obj1$optics_dbscan10_minptseps_cl0.25_curated) # because factors will returns all values (whatever its originale value)
levels(int_obj1$optics_dbscan10_minptseps_cl0.25_curated) <- 1:length(levels(int_obj1$optics_dbscan10_minptseps_cl0.25_curated))

levels(int_obj1$optics_dbscan10_minptseps_cl0.25_curated)[levels(int_obj1$optics_dbscan10_minptseps_cl0.25_curated) == "12"] <- NA

table(int_obj1$optics_dbscan10_minptseps_cl0.25_curated)






#



